[200~---
title: "databaseMLR"
output: html_document
date: "2023-11-29"
---

```{r, include = F, warning=F, message=F}
# front-matter
rm(list = ls()) #clear the workspace

library(tidyverse)
library(RPostgres)
library(mosaic)
library(ggformula)
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

```

Now load the sql

```{r}
db_user <- rstudioapi::askForPassword("Enter Your Username: ")
db_password <- rstudioapi::askForPassword("Enter Your Password: ")


canCon <- dbCanConnect(RPostgres::Postgres(),
  dbname = 'csci403',
  host = 'codd.mines.edu',
  port = '5433',
  user = db_user,
  password = db_password)

con <- dbConnect(RPostgres::Postgres(),
  dbname = 'csci403',
  host = 'codd.mines.edu',
  port = '5433',
  user = db_user,
  password = db_password)
```

```{r}
if (canCon) {
  cat("Connected to PostgreSQL\n")

  #query <- "SET SEARCH_PATH TO f23_group14;"
  #result <- dbGetQuery(con, query)

query <- "SELECT pi.player,pi.salary,pi.adjustedsalary,pi.experience,g, gs, mp,x3p_percent,x2p_percent,fg_percent,e_fg_percent,ft_percent,orb,drb,ast,stl,blk,tov,pf,pts FROM f23_group14.player_stats as ps JOIN f23_group14.player_salaryinfo as pi ON pi.seas_id = ps.seas_id ;"
  req <- dbSendQuery(con, query)

  data <- dbFetch(req)
  data
} else {
  cat("Connection failed\n")
}
```

```{r}
  dbDisconnect(con)

```
```{r}
data[1459,]
mlr <- lm(adjustedsalary ~ pts + ast + orb + drb + stl + blk + g + gs + experience + mp +fg_percent+ x3p_percent + x2p_percent + e_fg_percent + ft_percent + tov + pf, data = data)
summary(mlr)

plot(mlr,which = c(1,2,5))
#sort(mlr$residuals)

```

```{r}

bestMod <- regsubsets(adjustedsalary ~ pts + ast + orb + drb + stl + blk + g + gs + experience + mp + x3p_percent + x2p_percent + e_fg_percent + fg_percent + ft_percent + tov + pf,data = data, nbest=1,method = 'exhaustive',nvmax = 16,really.big = TRUE)
summary(bestMod)
plot(bestMod, scale = "bic")
plot(bestMod, scale = "adjr2")
plot(bestMod, scale = "Cp")

```



```{r}

mlrBIC <- lm(adjustedsalary ~ pts + ast + orb + drb + stl + gs + experience + mp +fg_percent + x2p_percent + e_fg_percent, data = data)
mlrAR2 <- lm(adjustedsalary ~ pts + ast + orb + drb + stl + blk + gs + experience + mp +fg_percent   + x3p_percent +x2p_percent + e_fg_percent + fg_percent + ft_percent + tov + pf, data = data)
mlrCP <- lm(adjustedsalary ~ pts + ast + orb + drb + stl + blk + gs + experience + mp +fg_percent +x2p_percent + e_fg_percent + fg_percent + ft_percent + tov + pf, data = data)
#summary(mlr)
summary(mlrBIC)
#summary(mlrAR2)
#summary(mlrCP)


```
